-- MySQL Script generated by MySQL Workbench
-- Sat Sep 23 19:48:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dep_personnel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dep_personnel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dep_personnel` DEFAULT CHARACTER SET utf8 ;
USE `dep_personnel` ;

-- -----------------------------------------------------
-- Table `dep_personnel`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dep_personnel`.`employee` (
  `emp_id` INT UNSIGNED NOT NULL,
  `emp_surname` VARCHAR(45) NOT NULL,
  `emp_name` VARCHAR(45) NOT NULL,
  `emp_patronymic` VARCHAR(45) NOT NULL,
  `emp_passport_num` INT UNSIGNED NOT NULL,
  `emp_birth_date` DATE NOT NULL,
  `emp_work_experience` TINYINT UNSIGNED NULL,
  `emp_telephone_num` VARCHAR(16) NULL,
  `emp_chief_id` INT UNSIGNED NULL,
  UNIQUE INDEX `emp_passport_num_UNIQUE` (`emp_passport_num` ASC) VISIBLE,
  UNIQUE INDEX `emp_telephone_num_UNIQUE` (`emp_telephone_num` ASC) VISIBLE,
  UNIQUE INDEX `emp_id_UNIQUE` (`emp_id` ASC) VISIBLE,
  PRIMARY KEY (`emp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dep_personnel`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dep_personnel`.`company` (
  `cmp_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cmp_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cmp_id`),
  UNIQUE INDEX `cmp_id_UNIQUE` (`cmp_id` ASC) VISIBLE,
  UNIQUE INDEX `cmp_name_UNIQUE` (`cmp_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dep_personnel`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dep_personnel`.`order` (
  `ord_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ord_date` DATE NOT NULL,
  `ord_vacation` TINYINT(1) NULL,
  `ord_business_trip` TINYINT(1) NULL,
  `ord_prof_growth` TINYINT(1) NULL,
  `ord_contract` TINYINT(1) NULL,
  PRIMARY KEY (`ord_id`),
  UNIQUE INDEX `ord_id_UNIQUE` (`ord_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dep_personnel`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dep_personnel`.`contract` (
  `ctr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ctr_company_id` INT UNSIGNED NOT NULL,
  `ctr_employee_id` INT UNSIGNED NOT NULL,
  `ctr_preparation_date` DATE NOT NULL,
  `ctr_accept_date` DATE NOT NULL,
  `ctr_salary` INT UNSIGNED NOT NULL,
  `ctr_bonus` INT UNSIGNED NULL,
  `ctr_order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ctr_id`),
  UNIQUE INDEX `ctr_id_UNIQUE` (`ctr_id` ASC) VISIBLE,
  INDEX `fk_contract_company_idx` (`ctr_company_id` ASC) VISIBLE,
  INDEX `fk_contract_employee1_idx` (`ctr_employee_id` ASC) VISIBLE,
  INDEX `fk_contract_order1_idx` (`ctr_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_contract_company`
    FOREIGN KEY (`ctr_company_id`)
    REFERENCES `dep_personnel`.`company` (`cmp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_employee1`
    FOREIGN KEY (`ctr_employee_id`)
    REFERENCES `dep_personnel`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_order1`
    FOREIGN KEY (`ctr_order_id`)
    REFERENCES `dep_personnel`.`order` (`ord_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dep_personnel`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dep_personnel`.`position` (
  `pos_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pos_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pos_id`),
  UNIQUE INDEX `pos_id_UNIQUE` (`pos_id` ASC) VISIBLE,
  UNIQUE INDEX `pos_name_UNIQUE` (`pos_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dep_personnel`.`m2m_employee_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dep_personnel`.`m2m_employee_position` (
  `emp_id` INT UNSIGNED NOT NULL,
  `pos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`emp_id`, `pos_id`),
  INDEX `fk_employee_has_position_position1_idx` (`pos_id` ASC) VISIBLE,
  INDEX `fk_employee_has_position_employee1_idx` (`emp_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_has_position_employee1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `dep_personnel`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_position_position1`
    FOREIGN KEY (`pos_id`)
    REFERENCES `dep_personnel`.`position` (`pos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dep_personnel`.`dismiss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dep_personnel`.`dismiss` (
  `dsm_id` INT UNSIGNED NOT NULL,
  `dsm_employee_id` INT UNSIGNED NOT NULL,
  `dsm_prepartion_date` DATE NOT NULL,
  `dsm_dismiss_date` DATE NOT NULL,
  `dsm_cause` VARCHAR(45) NOT NULL,
  `dsm_pay` VARCHAR(45) NULL,
  `dsm_order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`dsm_id`),
  UNIQUE INDEX `dsm_id_UNIQUE` (`dsm_id` ASC) VISIBLE,
  INDEX `fk_dismiss_employee1_idx` (`dsm_employee_id` ASC) VISIBLE,
  INDEX `fk_dismiss_order1_idx` (`dsm_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_dismiss_employee1`
    FOREIGN KEY (`dsm_employee_id`)
    REFERENCES `dep_personnel`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dismiss_order1`
    FOREIGN KEY (`dsm_order_id`)
    REFERENCES `dep_personnel`.`order` (`ord_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dep_personnel`.`vacation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dep_personnel`.`vacation` (
  `vac_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vac_emploee_id` INT UNSIGNED NOT NULL,
  `vac_preparation_date` DATE NOT NULL,
  `vac_days_num` INT NOT NULL,
  `vac_pay_period` INT NULL,
  `vac_order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`vac_id`),
  UNIQUE INDEX `vac_id_UNIQUE` (`vac_id` ASC) VISIBLE,
  INDEX `fk_vacation_employee1_idx` (`vac_emploee_id` ASC) VISIBLE,
  INDEX `fk_vacation_order1_idx` (`vac_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_vacation_employee1`
    FOREIGN KEY (`vac_emploee_id`)
    REFERENCES `dep_personnel`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vacation_order1`
    FOREIGN KEY (`vac_order_id`)
    REFERENCES `dep_personnel`.`order` (`ord_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dep_personnel`.`business_trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dep_personnel`.`business_trip` (
  `bt_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bt_destination` VARCHAR(45) NOT NULL,
  `bt_period_days` INT UNSIGNED NOT NULL,
  `bt_start_date` DATE NOT NULL,
  `bt_order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`bt_id`),
  UNIQUE INDEX `bt_id_UNIQUE` (`bt_id` ASC) VISIBLE,
  INDEX `fk_business_trip_order1_idx` (`bt_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_business_trip_order1`
    FOREIGN KEY (`bt_order_id`)
    REFERENCES `dep_personnel`.`order` (`ord_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dep_personnel`.`m2m_business_trip_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dep_personnel`.`m2m_business_trip_employee` (
  `business_trip_bt_id` INT UNSIGNED NOT NULL,
  `employee_emp_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`business_trip_bt_id`, `employee_emp_id`),
  INDEX `fk_business_trip_has_employee_employee1_idx` (`employee_emp_id` ASC) VISIBLE,
  INDEX `fk_business_trip_has_employee_business_trip1_idx` (`business_trip_bt_id` ASC) VISIBLE,
  CONSTRAINT `fk_business_trip_has_employee_business_trip1`
    FOREIGN KEY (`business_trip_bt_id`)
    REFERENCES `dep_personnel`.`business_trip` (`bt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_business_trip_has_employee_employee1`
    FOREIGN KEY (`employee_emp_id`)
    REFERENCES `dep_personnel`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dep_personnel`.`professional_growth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dep_personnel`.`professional_growth` (
  `pg_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pg_employee_id` INT UNSIGNED NOT NULL,
  `pg_prev_position` INT UNSIGNED NOT NULL,
  `pg_new_position` INT UNSIGNED NOT NULL,
  `pg_reassignment_type` VARCHAR(45) NOT NULL,
  `pg_order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pg_id`),
  UNIQUE INDEX `pg_id_UNIQUE` (`pg_id` ASC) VISIBLE,
  INDEX `fk_professional_growth_position1_idx` (`pg_prev_position` ASC) VISIBLE,
  INDEX `fk_professional_growth_position2_idx` (`pg_new_position` ASC) VISIBLE,
  INDEX `fk_professional_growth_employee1_idx` (`pg_employee_id` ASC) VISIBLE,
  INDEX `fk_professional_growth_order1_idx` (`pg_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_professional_growth_position1`
    FOREIGN KEY (`pg_prev_position`)
    REFERENCES `dep_personnel`.`position` (`pos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professional_growth_position2`
    FOREIGN KEY (`pg_new_position`)
    REFERENCES `dep_personnel`.`position` (`pos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professional_growth_employee1`
    FOREIGN KEY (`pg_employee_id`)
    REFERENCES `dep_personnel`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professional_growth_order1`
    FOREIGN KEY (`pg_order_id`)
    REFERENCES `dep_personnel`.`order` (`ord_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
